### ISSUE TITLE
No voice response to say it worked.

### ISSUE THREAD

**Issue by cooljimy84** [ChristopherRogers1991/mycroft-irsend#2]
Not sure if this is by design, but i don't get a vocal response to say it worked.

**Comment by ChristopherRogers1991** [comment]
Hey @cooljimy84,

This is by design. My personal opinion was that it was better to only say something if there was an error. This is largely because in the successful case, there's generally some other source of feedback. For example, if you ask Mycroft to turn on your TV, the TV should turn on; anything Mycroft said at that point would be redundant.

That said, it is just my opinion, and I could add a verbose setting, allowing the user to indicate if they'd like Mycroft to speak on success. This is the approach I took with the Hue skill (https://github.com/ChristopherRogers1991/mycroft-hue/blob/master/README.md). 

Let me know if this is something you'd like me to add (or, feel free to make a PR, if you'd like to implement it).

-Chris

**Comment by cooljimy84** [comment]
I just added
`        self.speak('By your command')`
to a new line at 147 as I'm testing remotely.

Now you've said that, I agree totally.
